spring.application.name=backend
spring.mongodb.auto-index-creation=true
server.port=8080
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.data.mongodb.auto-index-creation=true

jwt.secret=jwtsecretkeyjwtsecretkeyjwtsecretkey
jwt.expiration-ms=86400000

crypto.scheduler.enabled=true
crypto.scheduler.update-interval=15

app.seed.force=true
