spring.application.name=backend
spring.mongodb.uri=mongodb://localhost:27017/cryptowatch
spring.mongodb.database=cryptowatch

jwt.secret=ThisIsASecretKeyForJWTGenerationThatIsAtLeast256BitsLong!
jwt.expiration-ms=86400000