spring.application.name=backend
spring.mongodb.uri=mongodb://localhost:27017/cryptowatch
spring.mongodb.database=cryptowatch
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

jwt.secret=ThisIsASecretKeyForJWTGenerationThatIsAtLeast256BitsLong!
jwt.expiration-ms=86400000